### ISSUE TITLE
Версии пакетов

### ISSUE THREAD

**Issue by shude** [sitkoru/yandex-direct-api#42]
В связи с выходом Symfony 5, необходимо изменить версию symfony/validator на ~5.0.0 , для того чтобы была возможность установить библиотеку в Symfony 5 проекте.
Так же, обновить версии doctrine/annotations до 1.8 и doctrine/cache до 1.10

На данный момент конфликтов с этими версиями не обнаружил, библиотека работает.
Мой вариант версий пакетов:
```
"symfony/validator": "^5.0",
"doctrine/annotations": "^1.8.0",
"doctrine/cache": "^1.8.0"
```

**Comment by SonicGD** [comment]
Здравствуйте. Спасибо за предложение.

Я так понимаю, в этом случае библиотека не будет устанавливаться в проект с более старым Symfony. Возможно стоит написать какой-то более широкий селектор версии, например 
` "symfony/validator": ">=4.3.4"`? 

У нас нету проектов на Symfony, если у вас есть возможность проверить такой вариант на 4 и 5 версиях - будет здорово. Если нет - я постараюсь на неделе сам потестировать.

**Comment by shude** [comment]
Я займусь

**Comment by SonicGD** [comment]
Исправлено в https://github.com/sitkoru/yandex-direct-api/pull/47
