### ISSUE TITLE
Новые поля в ElementEnum

### ISSUE THREAD

**Issue by shude** [sitkoru/yandex-direct-api#43]
В ``` directapi\common\enum\clients\ElementEnum ``` добавить две новые константы

```php
public const GENERAL_DOMAIN_BLACKLIST_SIZE = 'GENERAL_DOMAIN_BLACKLIST_SIZE';
public const VIDEO_DOMAIN_BLACKLIST_SIZE = 'VIDEO_DOMAIN_BLACKLIST_SIZE';
```

**Comment by SonicGD** [comment]
Добрый день. Не хотите сделать pull request с этими правками?

**Comment by shude** [comment]
Выяснил, что полей появилось больше. Сейчас тестирую, да я займусь этой задачей

**Comment by SonicGD** [comment]
Исправлено в https://github.com/sitkoru/yandex-direct-api/pull/46
