### ISSUE TITLE
Сделать необязательным параметр token в конструкторе

### ISSUE THREAD

**Issue by shude** [sitkoru/yandex-direct-api#44]
Было бы не плохо, сделать параметр $token в ``` directapi/DirectApiService::__constructor() ``` не обязательным, а так же добавить set метод для токена.

Это позволит создавать экземпляры ```DirectApiService``` до того как станет известно какой токен будет использоваться. Например при использовании DependencyInjection , сейчас мы должны явно настроить с каким токеном он будет создаваться, а это не всегда возможно.

**Comment by SonicGD** [comment]
Добрый день. Да, хорошая идея, можно реализовать. Если есть желание - можете сами pull request прислать. Если нет - мы займёмся на неделе.

**Comment by shude** [comment]
Я у себя в форке уже реализовал, тестирую.  Сделаю pull request, когда проверю полноценно

**Comment by SonicGD** [comment]
Исправлено в https://github.com/sitkoru/yandex-direct-api/pull/48
